# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  net6shcart:
    image: net6shcart
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7294:7294
      - 5127:5127
